# Uncomment the next line to define a global platform for your project
platform :ios, '10'

target 'NHAuctionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NHAuctionApp
  pod 'AgoraRtcEngine_iOS'
  pod 'JWTDecode', '~> 2.6'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'MarqueeLabel'
  pod 'FirebaseDynamicLinks'
end
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
